# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "archives"
  parent = ""
  # you can add extra information before the name (HTML format is supported), such as icons
  pre = ""
  # you can add extra information after the name (HTML format is supported), such as icons
  post = ""
  name = "Archives"
  url = "/archives/"
  # title will be shown when you hover on this menu link
  title = ""
  weight = 1
  # FixIt 0.2.14 | NEW add user-defined content to menu items
  [main.params]
    # add css class to a specific menu item
    class = ""
    # whether set as a draft menu item whose function is similar to a draft post/page
    draft = false
    # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
    icon = "fa-solid fa-archive"
    # FixIt 0.2.16 | NEW set menu item type, optional values: ["mobile", "desktop"]
    type = ""
[[main]]
  identifier = "categories"
  parent = ""
  pre = ""
  post = ""
  name = "Categories"
  url = "/categories/"
  title = ""
  weight = 2
  [main.params]
    icon = "fa-solid fa-folder-tree"
[[main]]
  identifier = "tags"
  parent = ""
  pre = ""
  post = ""
  name = "Tags"
  url = "/tags/"
  title = ""
  weight = 3
  [main.params]
    icon = "fa-solid fa-tags"
#-----------------------------------------

# [languages]
#   [languages.en]
#     languageName = "English"
#     weight = 1
#     disabled = false
#     languageCode = "en"
#     contentDir = "content/en"  # Conteúdo em inglês
#     [languages.en.params]
#       logo = "/logo.svg"
#       disableTextInHeader = true
#       description = "Tabletop and card games producer and publisher."
#       keywords = ["tabletop games", "board games", "card games", "impossibilis"]
#       displayName = "EN"
#       isoCode = "en"
#       rtl = false
#     [languages.en.menu]
#       [[languages.en.menu.main]]
#         name = "About"
#         url = "/en/about/"
#         weight = 10
#       [[languages.en.menu.main]]
#         name = "Games"
#         url = "/en/games/"
#         weight = 20
#       [[languages.en.menu.main]]
#         name = "News"
#         url = "/en/news/"
#         weight = 30
#       [[languages.en.menu.main]]
#         name = "Contact"
#         url = "/en/contact/"
#         weight = 40

#   [languages.pt]
#     disabled = false
#     languageCode = "pt"
#     languageName = "Português"
#     weight = 2
#     contentDir = "content/pt"  # Conteúdo em português
#     [languages.pt.params]
#       logo = "/logo.svg"
#       disableTextInHeader = true
#       description = "Produtora e editora de jogos de tabuleiro e cartas."
#       keywords = ["jogos de tabuleiro", "jogos de cartas", "impossibilis"]
#       displayName = "PT"
#       isoCode = "pt"
#       rtl = false
#       dateFormat = "2 January 2006"
#     [languages.pt.menu]
#       [[languages.pt.menu.main]]
#         name = "Acerca"
#         url = "/pt/about/"
#         weight = 10
#       [[languages.pt.menu.main]]
#         name = "Jogos"
#         url = "/pt/games/"
#         weight = 20
#       [[languages.pt.menu.main]]
#         name = "Novidades"
#         url = "/pt/news/"
#         weight = 30
#       [[languages.pt.menu.main]]
#         name = "Contacto"
#         url = "/pt/contact/"
#         weight = 40