# -------------------------------------------------------------------------------------
# Modules Configure
# See: https://gohugo.io/hugo-modules/configuration/#module-config-imports
# -------------------------------------------------------------------------------------

# [[imports]]
#   path = "github.com/hugo-fixit/FixIt"
#   ignoreConfig = true  # Desativa toda a config do módulo, incluindo i18n

# [[imports]]
#   path = "github.com/hugo-fixit/shortcode-docs-bookmark"

# [hugoVersion]
#   extended = true
#   min = "0.132.0"

#ignoreConfig = ["i18n"]